server:
  port: 8002

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db
    username: root
    password: root
    
  jpa:
    hibernate:
      ddl-auto: update
      database-platform: org.hibernate.dialect.MySQLInnoDBDialect
      database: mysql

  jackson:
    mapper:
      accept-case-insensitive-properties: true

      
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    hostname: localhost
    preferIpAddress: true